# This docker-compose file is for deploying a fully working backend

version: '3.7'

services:
    sqe-database:
        image: qumranica/sqe-database:latest
        container_name: SQE_Database
        environment:
        - MYSQL_ROOT_PASSWORD=none
        - MYSQL_DATABASE=SQE
        expose:
        - "3306"
        ports:
        - "3307:3306"
    sqe-http:
        container_name: SQE_HTTP_API
        image: qumranica/sqe-http-api:0.9.10
        restart: always
        ports:
            - 5000:5000
        environment:
            ## Database settings (must match the settings for sqe-database above)
            - MYSQL_HOST=sqe-database # in docker-compose a service name can be used as a hostname (it will route to that container)
            - MYSQL_PORT=3306
            - MYSQL_USER=root
            - MYSQL_PASSWORD=none
            - MYSQL_DATABASE=SQE
            
            ## Email settings (account that mails user registration information)
            - MAILER_EMAIL_ADDRESS=qumranica@gmail.com
            - MAILER_EMAIL_USERNAME=qumranica@gmail.com
            - MAILER_EMAIL_PASSWORD=CxC-xga-0kn-JUr
            - MAILER_EMAIL_SMTP_URL=smtp.gmail.com
            - MAILER_EMAIL_SMTP_PORT=587
            - MAILER_EMAIL_SMTP_SECURITY=StartTlsWhenAvailable #The options are "None", "Auto", "SslOnConnect", "StartTls", and "StartTlsWhenAvailable"

            ## Partner website settings (website that calls the user registration functions)
            - WEBSITE_HOST=https://9090.digitalbibleonline.org

            ## Dotnet telemetry optout
            - DOTNET_CLI_TELEMETRY_OPTOUT=1

            ## Secret string for API JWT generation (the API will error if this is too short)
            - SQE_API_SECRET=kjdsavc987342r8gnx%%6bq1@@lknsdciqeurhfwiurbcea-+++

            ## Logging levels, valid values are: Verbose, Debug, Information, Warning, Error, Fatal
            - API_LOGLEVEL=Information # Log level for API generated messages
            - DOTNET_LOGLEVEL=Warning # Log level for dotnet core messages and Microsoft tooling
            - SYSTEM_LOGLEVEL=Warning # Leg level for system level messages

            ## Redis SignalR backplane settings for horizontal scaling of the realtime API (disabled by default)
            - USE_REDIS=false # Use a Redis backplane to horizontally scale the realtime API
            # - REDIS_HOST=redis-cache
            # - REDIS_PORT=6379
            # - REDIS_PASSWORD=password123

            ## Server options
            - Http_Server=true # Run the API HTTP server
        volumes:
            - ./logs:/app/logs # Logs are written to ./log on the host system (relative to the folder with docker-compose.yml)
        depends_on:
            - sqe-database
